---
- name: DB | create database
  community.mysql.mysql_db:
    login_unix_socket: "/run/mysqld/mysqld.sock"
    login_user: "root"
    login_password: "{{ mariadb_root_password }}"
    name: "{{ item }}"
    state: present
  delegate_to: "{{ groups['mariadb'][0] }}"
  run_once: true
  no_log: true
  loop: "{{ nova_db }}"

- name: DB | set user
  community.mysql.mysql_user:
    login_unix_socket: "/run/mysqld/mysqld.sock"
    login_user: "root"
    login_password: "{{ mariadb_root_password }}"
    name: "{{ os_service_name }}"
    host: "{{ item[0] }}"
    password: "{{ db_password }}"
    priv: "{{ item[1] }}.*:ALL,GRANT"
    append_privs: true
  loop: "{{ openstack_mariadb_acl_cidr | product(nova_db) | list }}"
  no_log: true
...
