---
- name: Delete | import common tasks
  tags:
    - nova
    - openstack
  ansible.builtin.import_tasks: "common.yml"

- name: Delete | purge controller packages
  tags:
    - nova
    - openstack
  ansible.builtin.apt:
    name: "{{ item }}"
    purge: true
    state: absent
  loop: "{{ controller_packages }}"
  become: true
  when: inventory_hostname in groups['controller']

- name: Delete | purge compute packages
  tags:
    - nova
    - openstack
  ansible.builtin.apt:
    name: "{{ item }}"
    purge: true
    state: absent
  loop: "{{ compute_packages }}"
  become: true
  when: inventory_hostname in groups['compute']

- name: DB | delete database
  tags:
    - nova
    - openstack
  community.mysql.mysql_db:
    login_unix_socket: "/run/mysqld/mysqld.sock"
    login_user: "root"
    login_password: "{{ mariadb_root_password }}"
    name: "{{ item }}"
    state: absent
  delegate_to: "{{ groups['mariadb'][0] }}"
  loop: "{{ nova_db }}"
  run_once: true
  no_log: true

- name: Delete | delete config directory
  tags:
    - nova
    - openstack
  ansible.builtin.file:
    path: "{{ os_conf_dir }}"
    state: absent
  become: true
...
