---
- name: Setup libvirt | get client.cinder ceph keyring
  ansible.builtin.command: ceph auth get-or-create client.cinder
  register: client_cinder_keyring
  become: true
  delegate_to: "{{ groups['cinder'][0] }}"
  run_once: true

- name: Setup libvirt | check if cinder user exists
  ansible.builtin.user:
    name: cinder
  check_mode: true
  register: is_cinder
  become: true

- name: Setup libvirt | copy client.cinder ceph keyring
  ansible.builtin.copy:
    content: "{{ client_cinder_keyring.stdout }}\n"
    dest: "/etc/ceph/ceph.client.cinder.keyring"
    owner: "{{ is_cinder.changed | ternary('nova', 'cinder') }}"
    group: "nova"
    mode: "0640"
  become: true

- name: Setup libvirt | get client.cinder key
  ansible.builtin.command: ceph auth get-key client.cinder
  register: result
  become: true
  delegate_to: "{{ groups['cinder'][0] }}"
  run_once: true

- name: Setup libvirt | set fact for client.cinder key
  ansible.builtin.set_fact:
    cinder_key: "{{ result.stdout }}"

- name: Setup libvirt | template secret.xml
  ansible.builtin.template:
    dest: "/tmp/secret.xml"
    src: "secret.xml.j2"

- name: Setup libvirt | virsh secret-define
  ansible.builtin.shell: virsh secret-define --file /tmp/secret.xml
  become: true

- name: Setup libvirt | virsh secret-set-value
  ansible.builtin.shell: >-
    virsh secret-set-value {{ rbd_secret }} --base64 {{ cinder_key }}
  become: true
...
