---
- name: Setup ssh keys | remove temporary directory for ssh keys
  ansible.builtin.file:
    path: "/tmp/sshkey"
    state: absent
  become: true
  delegate_to: "{{ groups['compute'][0] }}"
  run_once: true

- name: Setup ssh keys | create temporary directory for ssh keys
  ansible.builtin.file:
    path: "/tmp/sshkey"
    state: directory
    mode: 0755
  delegate_to: "{{ groups['compute'][0] }}"
  run_once: true

- name: Setup ssh keys | create ssh key pair
  ansible.builtin.command: >-
    ssh-keygen -t rsa -f /tmp/sshkey/id_rsa -N ''
  delegate_to: "{{ groups['compute'][0] }}"
  run_once: true

- name: Setup ssh keys | get ssh public key
  ansible.builtin.slurp:
    src: "/tmp/sshkey/id_rsa.pub"
  register: ssh_public_key
  delegate_to: "{{ groups['compute'][0] }}"
  run_once: true

- name: Setup ssh keys | get ssh private key
  ansible.builtin.slurp:
    src: "/tmp/sshkey/id_rsa"
  register: ssh_private_key
  delegate_to: "{{ groups['compute'][0] }}"
  run_once: true

- name: Setup ssh keys | create ssh directory on compute nodes
  ansible.builtin.file:
    path: "{{ nova_home }}/.ssh"
    state: directory
    owner: "{{ os_service_name }}"
    group: "{{ os_service_name }}"
    mode: 0755
  become: true
  when: inventory_hostname in groups['compute']

- name: Setup ssh keys | create ssh key files on compute nodes
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ nova_home }}/.ssh/{{ item.name }}"
    mode: "{{ item.mode }}"
    owner: "{{ os_service_name }}"
    group: "{{ os_service_name }}"
  become: true
  no_log: true
  loop:
    - {name: "authorized_keys", content: "{{ ssh_public_key.content | b64decode }}", mode: "0600"}
    - {name: "id_rsa.pub", content: "{{ ssh_public_key.content | b64decode }}", mode: "0644"}
    - {name: "id_rsa", content: "{{ ssh_private_key.content | b64decode }}", mode: "0600"}

- name: Setup ssh keys | create ssh config file on compute nodes
  ansible.builtin.blockinfile:
    path: "{{ nova_home }}/.ssh/config"
    create: true
    mode: "0600"
    owner: "{{ os_service_name }}"
    group: "{{ os_service_name }}"
    block: |
      StrictHostKeyChecking no
      UserKnownHostsFile /dev/null
  become: true

- name: Setup ssh keys | set nova shell to /bin/sh
  ansible.builtin.user:
    name: nova
    shell: "/bin/sh"
    state: present
  become: true

- name: Setup ssh keys | remove temporary directory for ssh keys
  ansible.builtin.file:
    path: "/tmp/sshkey"
    state: absent
  become: true
  delegate_to: "{{ groups['compute'][0] }}"
  run_once: true
...
