---
- name: Setup compute | copy init file
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode }}"
  loop: "{{ os_service_init_compute }}"
  become: true

- name: Setup compute | template configuration
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest + '.j2' }}"
    owner: "root"
    group: "{{ os_service_name }}"
    mode: "{{ item.mode }}"
    backup: true
  loop: "{{ os_service_compute_conf }}"
  become: true
  changed_when: true
  notify:
    - systemctl restart compute service

- name: Setup compute | flush handlers
  ansible.builtin.meta: flush_handlers

- name: Setup compute | include libvirt secret task
  ansible.builtin.include_tasks: libvirt_secret.yml
  when: '"ceph" in storage_backends'

- name: Setup compute | include ssh key tasks
  ansible.builtin.include_tasks: nova_sshkey.yml
...
