---
- name: Setup compute | mask libvirtd socket systemd service
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
  become: true
  loop: "{{ libvirtd_sockets }}"

- name: Setup compute | copy init file
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode }}"
  loop: "{{ os_service_init_compute }}"
  become: true

- name: Setup compute | template configuration
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest + '.j2' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ os_service_compute_conf }}"
  become: true
  changed_when: true
  notify:
    - systemctl restart compute service

# Since qemu-cloudpc does not change /usr/libexec/qemu-kvm,
# I need to do some extra work after installing it.
- name: Rocky Linux | check if qemu-kvm exists
  ansible.builtin.stat:
    path: "{{ qemu_bin.src }}"
  register: check_qemu_kvm
  when: install_custom_pkgs

- name: Rocky Linux | check if qemu-system-x86_64 exists
  ansible.builtin.stat:
    path: "{{ qemu_bin.dest }}"
  register: check_qemu_system_x86_64
  when: install_custom_pkgs

- name: Rocky Linux | back up file with new name
  ansible.builtin.copy:
    src: "{{ qemu_bin.src }}"
    dest: "{{ qemu_bin.src }}.{{ ansible_date_time.iso8601 }}"
    remote_src: true
    mode: "0755"
  become: true
  when:
    - install_custom_pkgs
    - check_qemu_kvm.stat.exists
    - check_qemu_system_x86_64.stat.exists

- name: Rocky Linux | symlink qemu-kvm to qemu-system-x86_64
  ansible.builtin.file:
    dest: "{{ qemu_bin.dest }}"
    src: "{{ qemu_bin.src }}"
    owner: "root"
    group: "root"
    state: link
  become: true
  when:
    - install_custom_pkgs
    - check_qemu_kvm.stat.exists
    - check_qemu_system_x86_64.stat.exists
# End of temporary custom package install fix.

- name: Setup compute | flush handlers
  ansible.builtin.meta: flush_handlers

- name: Setup compute | include libvirt secret task
  ansible.builtin.include_tasks: libvirt_secret.yml
  when: '"ceph" in storage_backends'

- name: Setup compute | include ssh key tasks
  ansible.builtin.include_tasks: nova_sshkey.yml
...
