---
- name: Setup compute | mask libvirtd socket systemd service
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
    masked: true
  become: true
  loop: "{{ libvirtd_sockets }}"

- name: Setup compute | copy init file
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode }}"
  loop: "{{ os_service_init_compute }}"
  become: true

- name: Setup | create systemd drop-in replacement directory
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ item }}.d"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  become: true
  loop: "{{ os_systemd_compute_service_name }}"

- name: Setup | create systemd drop-in replacement files for KillMode=mixed
  ansible.builtin.copy:
    dest: "/etc/systemd/system/{{ item }}.d/killmode.conf"
    content: |
      [Service]
      KillMode=mixed
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ os_systemd_compute_service_name }}"
  become: true
  notify:
    - systemctl restart compute service

- name: Setup | reload systemd
  ansible.builtin.command: >-
    systemctl daemon-reload
  become: true

- name: Setup compute | template configuration
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest + '.j2' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ os_service_compute_conf }}"
  become: true
  changed_when: true
  notify:
    - systemctl restart compute service

- name: Setup compute | flush handlers
  ansible.builtin.meta: flush_handlers

- name: Setup compute | include libvirt secret task
  ansible.builtin.include_tasks: libvirt_secret.yml
  when: '"ceph" in storage_backends'

- name: Setup compute | include ssh key tasks
  ansible.builtin.include_tasks: nova_sshkey.yml
...
