---
- name: Setup | copy init file
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode }}"
  loop: "{{ os_service_init_compute }}"
  become: true

- name: Setup | template configuration
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest + '.j2' }}"
    owner: "root"
    group: "{{ os_service_name }}"
    mode: "{{ item.mode }}"
    backup: true
  loop: "{{ os_service_compute_conf }}"
  become: true
  changed_when: true
  notify:
    - systemctl restart compute service

- name: Setup | get client.cinder ceph keyring
  ansible.builtin.command: ceph auth get-or-create client.cinder
  register: client_cinder_keyring
  become: true
  delegate_to: "{{ groups['cinder'][0] }}"
  run_once: true

- name: Setup | copy client.cinder ceph keyring
  ansible.builtin.copy:
    content: "{{ client_cinder_keyring.stdout }}\n"
    dest: "/etc/ceph/ceph.client.cinder.keyring"
    owner: "{{ os_service_name }}"
    group: "{{ os_service_name }}"
    mode: "0600"
  become: true

- name: Setup | get client.cinder key
  ansible.builtin.command: ceph auth get-key client.cinder
  register: result
  become: true
  delegate_to: "{{ groups['cinder'][0] }}"
  run_once: true

- name: Setup | set fact for client.cinder key
  ansible.builtin.set_fact:
    cinder_key: "{{ result.stdout }}"

- name: Setup | template secret.xml
  ansible.builtin.template:
    dest: "/tmp/secret.xml"
    src: "secret.xml.j2"

- name: Setup | virsh secret-define
  ansible.builtin.shell: virsh secret-define --file /tmp/secret.xml
  become: true

- name: Setup | virsh secret-set-value
  ansible.builtin.shell: "virsh secret-set-value {{ rbd_secret }} --base64 {{ cinder_key }}"
  become: true
...
