---
- name: Start | import common tasks
  tags: nova
  ansible.builtin.import_tasks: "common.yml"

- name: Start | start service
  tags: nova
  block:
    - name: Start | start service
      ansible.builtin.service:
        name: "{{ item }}"
        state: "started"
      become: true
      register: start_service
      failed_when: start_service.failed
      loop: "{{ os_systemd_service_name }}"
      when: inventory_hostname in groups['controller']
    - name: Start | start service
      ansible.builtin.service:
        name: "{{ item }}"
        state: "started"
      become: true
      register: start_service
      failed_when: start_service.failed
      loop: "{{ os_systemd_compute_service_name }}"
      when: inventory_hostname in groups['compute']
    - name: Start | wait until port is opened
      ansible.builtin.wait_for:
        host: "{{ ansible_host }}"
        port: "{{ nova_port }}"
        sleep: 2
        timeout: 10
        state: started
      when: inventory_hostname in groups['controller']
...
