---
- name: Ubuntu | Install prerequisite packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "{{ apt_state }}"
    update_cache: true
    allow_unauthenticated: false
  register: _apt
  until: not _apt.failed
  retries: 3
  delay: 3
  loop: "{{ prereq_pkgs }}"
  become: true

- name: Ubuntu | add openstack repository
  ansible.builtin.command: >-
    add-apt-repository -y cloud-archive:{{ openstack_release }}
  become: true

- name: Ubuntu | Install controller packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "{{ apt_state }}"
    update_cache: true
    allow_unauthenticated: false
  register: _apt
  until: not _apt.failed
  retries: 3
  delay: 3
  become: true
  loop: "{{ controller_packages }}"
  when: inventory_hostname in groups['controller']

- name: Ubuntu | Install compute packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "{{ apt_state }}"
    update_cache: true
    allow_unauthenticated: false
  register: _apt
  until: not _apt.failed
  retries: 3
  delay: 3
  become: true
  loop: "{{ compute_packages }}"
  when: inventory_hostname in groups['compute']
...
