---
- name: systemctl restart service
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: true
  register: _restart_service
  until: not _restart_service.failed
  retries: 3
  delay: 3
  become: true
  changed_when: false
  loop: "{{ os_systemd_service_name }}"

- name: systemctl restart compute service
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: true
  register: _restart_service
  until: not _restart_service.failed
  retries: 3
  delay: 3
  become: true
  changed_when: false
  loop: "{{ os_systemd_compute_service_name }}"
...
